// examples/react/src/views/topology.jsx
/*
 * @Description: 
 * @Author: 高浩然
 * @Date: 2021-10-11 16:56:45
 * @LastEditTime: 2021-10-12 11:46:58
 */
import React, { useEffect } from 'react';
import { Topology } from '../../../../dist/topology/topology';

const TopologyContainer = () => {
  useEffect(() => {
    window.topology = new Topology('topology');
  }, []);

  return (
    <div className='main' >
      <div className="topology" id="topology"></div>
    </div>
  );
};

export default TopologyContainer;

// examples/vue/src/components/Topology.vue
<!--
 * @Description: 
 * @Author: G
 * @Date: 2021-10-13 11:10:11
 * @LastEditTime: 2021-10-13 14:05:59
-->
<script setup lang="ts">
import { onMounted } from 'vue';
import '../../../../dist/topology/topology';

onMounted(() => {
  window.topology = new window.Topology('topology');
});
</script>

<template>
<div class='main' >
  <div class="topology" id="topology"></div>
</div>
</template>

<style scoped>

</style>
